### ISSUE TITLE
NodeJS RunExamples fails

### ISSUE THREAD

**Issue by gadelkareem** [treelogic-swe/aws-mock#31]
Trying to run the NodeJS examples but I got an Error:
```
> nodejs RunExamples.js runInstances i-87d89696 i-87d89697

/home/vagrant/aws-mock/example/nodejs/simple/RunInstancesExample.js:12
    ec2.runInstances(params, function getInstances(err, resp) {
        ^
TypeError: Cannot call method 'runInstances' of undefined
    at Object.exports.runInstances (/home/vagrant/aws-mock/example/nodejs/simple/RunInstancesExample.js:12:9)
    at runInstances (/home/vagrant/aws-mock/example/nodejs/RunExamples.js:53:25)
    at Object.<anonymous> (/home/vagrant/aws-mock/example/nodejs/RunExamples.js:23:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

It would be great if we can have command to create a random set of EC2s with different info for testing

**Comment by maxiaohao** [comment]
Hi gadelkareem, 
Thanks for raising this issue! 
The node.js example code has now been fixed - you can start the aws-mock daemon and then run the example client code like this: 
`node RunExamples runInstances` 
or 
`node RunExamples runInstances ami-12345678 t1.micro 3` (which starts 3 instances at a time).
