### ISSUE TITLE
Aws-mock's docker Container creation failed due to gradle-cobertura-plugin

### ISSUE THREAD

**Issue by Davinder2me** [treelogic-swe/aws-mock#36]
Here is logs from docker container. Please let me know if there is anything i am missing. Locally, it is working fine and if remove the cobertura plugin from gradle build file, it works fine too in docker container.

Thanks
Davinder

Download https://plugins.gradle.org/m2/net/saliman/gradle-cobertura-plugin/2.3.2/gradle-cobertura-plugin-2.3.2.pom
Download https://plugins.gradle.org/m2/net/saliman/gradle-cobertura-plugin/2.3.2/gradle-cobertura-plugin-2.3.2.jar

FAILURE: Build failed with an exception.

* Where:
Build file '/project/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'aws-mock'.
> Could not create plugin of type 'CoberturaPlugin'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'aws-mock'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
	at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
	at org.gradle.configuration.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:44)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:464)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:77)
	at org.gradle.configuration.DefaultBuildConfigurer$ConfigureProject.execute(DefaultBuildConfigurer.java:38)
	at org.gradle.configuration.DefaultBuildConfigurer$ConfigureProject.execute(DefaultBuildConfigurer.java:36)
	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:440)
	at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:435)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:32)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:38)
	at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:39)
	at org.gradle.launcher.exec.InProcessGradleLauncherActionExecuter.execute(InProcessGradleLauncherActionExecuter.java:25)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
	at org.gradle.api.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:48)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.Main.main(Main.java:39)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:26)
Caused by: org.gradle.api.plugins.PluginInstantiationException: Could not create plugin of type 'CoberturaPlugin'.
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:65)
	at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:106)
	at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPluginInternal(DefaultProjectsPluginContainer.java:71)
	at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(DefaultProjectsPluginContainer.java:37)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:101)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:32)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:72)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
	at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:846)
	at org.gradle.api.Project$apply.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
	at build_2vgou50bajsuscsfe7ojomoo18.run(/project/build.gradle:25)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 30 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/plugins/PluginAware
	at net.saliman.gradle.plugin.cobertura.CoberturaPlugin.$getStaticMetaClass(CoberturaPlugin.groovy)
	at net.saliman.gradle.plugin.cobertura.CoberturaPlugin.<init>(CoberturaPlugin.groovy)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:62)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:63)
	... 43 more
Caused by: java.lang.ClassNotFoundException: org.gradle.api.plugins.PluginAware
	... 47 more

**Comment by maxiaohao** [comment]
Hi, 

The cobertura plugin is configured according to official guide: https://plugins.gradle.org/plugin/net.saliman.cobertura

Here is a successful example of clean `gradle jettyRun` build in a container from the popular gradle image `frekele/gradle` (I use it's gradle versioned 2.14.1) and I also tried `gradle clean coberturaCheck check` in it which also passed as expected. 

```
dev1:/tmp$ git clone git@github.com:treelogic-swe/aws-mock.git
Cloning into 'aws-mock'...
remote: Counting objects: 15898, done.
remote: Total 15898 (delta 0), reused 0 (delta 0), pack-reused 15898
Receiving objects: 100% (15898/15898), 45.38 MiB | 6.53 MiB/s, done.
Resolving deltas: 100% (10983/10983), done.
Checking connectivity... done.
dev1:/tmp$ 
dev1:/tmp$ sudo docker run -v /tmp/aws-mock:/aws-mock frekele/gradle:2.14.1-jdk8u101 sh -c "cd /aws-mock && gradle jettyRun"
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 40-import-trusted-ssl-certs.sh: executing... 
[cont-init.d] 40-import-trusted-ssl-certs.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Download http://repo2.maven.org/maven2/net/saliman/gradle-cobertura-plugin/2.3.2/gradle-cobertura-plugin-2.3.2.pom
Download http://repo2.maven.org/maven2/net/saliman/gradle-cobertura-plugin/2.3.2/gradle-cobertura-plugin-2.3.2.jar
:compileJava
Download http://repo2.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
Download http://repo2.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download http://repo2.maven.org/maven2/org/apache/apache/9/apache-9.pom
Download http://repo2.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.pom
Download http://repo2.maven.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
Download http://repo2.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.pom
Download http://repo2.maven.org/maven2/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.pom
Download http://repo2.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download http://repo2.maven.org/maven2/com/treelogic-swe/cxf-stub/1.0.2/cxf-stub-1.0.2.pom
Download http://repo2.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.pom
Download http://repo2.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
Download http://repo2.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
Download http://repo2.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar
Download http://repo2.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar
Download http://repo2.maven.org/maven2/org/freemarker/freemarker/2.3.20/freemarker-2.3.20.jar
Download http://repo2.maven.org/maven2/com/treelogic-swe/cxf-stub/1.0.2/cxf-stub-1.0.2.jar
Download http://repo2.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
Download http://repo2.maven.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jettyRunSLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/gradle-2.14.1/lib/gradle-logging-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

[2016-10-28 00:53:28,649] [WARN ] [main] properties file 'aws-mock.properties' not found in classpath, no default property in 'aws-mock-default.properties' will be overridden (com.tlswe.awsmock.common.util.PropertiesUtils.java:75)
[2016-10-28 00:53:28,889] [INFO ] [main] aws-mock started. (com.tlswe.awsmock.common.listener.AppServletContextListener.java:75)

```

Maybe it's due to the version of gradle you are using. And please try frekele's gradle (both version 3 and 2). 
All frekele's gradle images can be found here: https://hub.docker.com/r/frekele/gradle/ 
I hope that could help you figure the issue out.

**Comment by Davinder2me** [comment]
Thanks. I changed to docker file to use frekele/gradle image. It fixed the issue. I sent pull request with my others too.
